name: allvideodownloader
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_youtube_downloader: ^0.0.5
  provider: ^6.0.3
  facebook_video_download: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 
  assets:
    - assets/logovid.png
    - assets/pichome.png
    - assets/youtube.png
    - assets/fblogo.png
  uses-material-design: true
 
